# Docker Compose file version
version: '3.8'

# Define the services (containers) for the application
services:
  # Service name for your GUI application
  ars-gui:
    # Build the Docker image from the Dockerfile in the current directory
    build: .
    # Set a container name for easier management
    container_name: ars_gui_container
    # Environment variables needed to connect the container's display to the host's X server
    # This allows the GUI to appear on your screen.
    # NOTE: This setup is for Linux hosts. For Windows/macOS, you'll need an X Server like XQuartz (macOS) or VcXsrv (Windows).
    environment:
      - DISPLAY=${DISPLAY}
    # Mount the host's X11 socket into the container
    # This allows the container to communicate with the host's display server.
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix